LIGHT = {
    "bg":          "#F0F4F8",
    "header_bg":   "#1A1A2E",
    "header_fg":   "#FFFFFF",
    "grid_bg":     "#FFFFFF",
    "box_border":  "#1A1A2E",
    "cell_border": "#B0BEC5",
    "clue_bg":     "#DDE8F5",
    "clue_fg":     "#1A1A2E",
    "user_bg":     "#FFFFFF",
    "user_fg":     "#1565C0",
    "error_bg":    "#FFCDD2",
    "error_fg":    "#B71C1C",
    "btn_primary": "#1A1A2E",
    "btn_fg":      "#FFFFFF",
    "btn_accent":  "#0D7377",
    "btn_danger":  "#C62828",
    "btn_warn":    "#E65100",
    "status_fg":   "#37474F",
    "select_bg":   "#FFFDE7",
    "input_bg":    "#FFFFFF",
    "input_fg":    "#1A1A2E",
    "label_fg":    "#1A1A2E",
    "card_bg":     "#E8EEF4",
}

DARK = {
    "bg":          "#121212",
    "header_bg":   "#1F1B2E",
    "header_fg":   "#E0E0E0",
    "grid_bg":     "#1E1E1E",
    "box_border":  "#BB86FC",
    "cell_border": "#444444",
    "clue_bg":     "#2A2A3E",
    "clue_fg":     "#CE93D8",
    "user_bg":     "#1E1E1E",
    "user_fg":     "#80CBC4",
    "error_bg":    "#4E1010",
    "error_fg":    "#EF9A9A",
    "btn_primary": "#BB86FC",
    "btn_fg":      "#121212",
    "btn_accent":  "#03DAC6",
    "btn_danger":  "#CF6679",
    "btn_warn":    "#FFAB40",
    "status_fg":   "#9E9E9E",
    "select_bg":   "#2E2B1F",
    "input_bg":    "#2A2A2A",
    "input_fg":    "#E0E0E0",
    "label_fg":    "#E0E0E0",
    "card_bg":     "#1F1F2E",
}
